# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisUI(object):
    def setupUi(self, JarvisUI):
        JarvisUI.setObjectName("JarvisUI")
        JarvisUI.resize(1391, 784)
        JarvisUI.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(JarvisUI)
        self.centralwidget.setObjectName("centralwidget")

        # self.bg_Image = QtWidgets.QLabel(self.centralwidget)
        # self.bg_Image.setGeometry(QtCore.QRect(0, 0, 1366, 768))
        # font = QtGui.QFont()
        # font.setFamily("Segoe UI")
        # self.bg_Image.setFont(font)
        # self.bg_Image.setFrameShape(QtWidgets.QFrame.Box)
        # self.bg_Image.setFrameShadow(QtWidgets.QFrame.Plain)
        # self.bg_Image.setLineWidth(1)
        # self.bg_Image.setText("")
        # # self.bg_Image.setPixmap(QtGui.QPixmap("images/bg.jp"))
        # self.bg_Image.setScaledContents(True)
        # self.bg_Image.setObjectName("bg_Image")


        self.cammandArea = QtWidgets.QLabel(self.centralwidget)
        self.cammandArea.setEnabled(True)
        self.cammandArea.setGeometry(QtCore.QRect(260, 340, 1080, 351))
        self.cammandArea.setText("")
        self.cammandArea.setPixmap(QtGui.QPixmap("images/—Pngtree—blue science fiction grid iron_112370.png"))
        self.cammandArea.setScaledContents(True)
        self.cammandArea.setObjectName("cammandArea")


        self.mainLabel = QtWidgets.QLabel(self.centralwidget)
        self.mainLabel.setEnabled(True)
        self.mainLabel.setGeometry(QtCore.QRect(477, 40, 411, 281))
        self.mainLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mainLabel.setText("")
        self.mainLabel.setPixmap(QtGui.QPixmap("images/GIF.gif"))
        self.mainLabel.setScaledContents(True)
        self.mainLabel.setObjectName("mainLabel")


        self.dateLabel = QtWidgets.QLabel(self.centralwidget)
        self.dateLabel.setGeometry(QtCore.QRect(1140, 20, 200, 35))
        font = QtGui.QFont()
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateLabel.setFont(font)
        self.dateLabel.setStyleSheet("color: rgb(0, 85, 255);")
        self.dateLabel.setObjectName("dateLabel")


        self.timeLabel = QtWidgets.QLabel(self.centralwidget)
        self.timeLabel.setGeometry(QtCore.QRect(1140, 50, 200, 35))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.timeLabel.setFont(font)
        self.timeLabel.setStyleSheet("color: rgb(0, 85, 255);\n"
"border-bottom-color: 5px solid rgb(0, 0, 255);")
        self.timeLabel.setObjectName("timeLabel")

        self.buttonsLabel = QtWidgets.QLabel(self.centralwidget)
        self.buttonsLabel.setGeometry(QtCore.QRect(20, 620, 261, 61))
        self.buttonsLabel.setStyleSheet("border:4px solid rgb(0, 85, 255);")
        self.buttonsLabel.setObjectName("buttonsLabel")


        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(28, 630, 120, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.startButton.setFont(font)
        self.startButton.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"border:none;")
        self.startButton.setObjectName("startButton")


        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(153, 630, 120, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.stopButton.setFont(font)
        self.stopButton.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"border: none;")
        self.stopButton.setObjectName("stopButton")


        self.centerJarvisLabel = QtWidgets.QLabel(self.centralwidget)
        self.centerJarvisLabel.setGeometry(QtCore.QRect(584, 88, 211, 191))
        self.centerJarvisLabel.setText("")
        self.centerJarvisLabel.setPixmap(QtGui.QPixmap("images/pngegg.png"))
        self.centerJarvisLabel.setScaledContents(True)
        self.centerJarvisLabel.setObjectName("centerJarvisLabel")
        self.centerJarvisLabel.setStyleSheet("background:none;")


        self.featuresLabel = QtWidgets.QLabel(self.centralwidget)
        self.featuresLabel.setGeometry(QtCore.QRect(20, 250, 241, 301))
        self.featuresLabel.setStyleSheet("border:4px solid rgb(0, 85, 255);")
        self.featuresLabel.setObjectName("featuresLabel")


        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 290, 221, 251))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 85, 255);\n"
"border: none;\n"
"")
        self.plainTextEdit.setObjectName("plainTextEdit")


        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 250, 241, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setIndent(-1)
        self.label.setObjectName("label")


        self.performanceLabel = QtWidgets.QLabel(self.centralwidget)
        self.performanceLabel.setGeometry(QtCore.QRect(20, 20, 311, 191))
        self.performanceLabel.setStyleSheet("border:4px solid rgb(0, 85, 255);")
        self.performanceLabel.setObjectName("performanceLabel")


        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 311, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setIndent(-1)
        self.label_2.setObjectName("label_2")

        self.CPU = QtWidgets.QLabel(self.centralwidget)
        self.CPU.setGeometry(QtCore.QRect(30, 60, 71, 41))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.CPU.setFont(font)
        self.CPU.setStyleSheet("color: rgb(0, 85, 255);\n"
"border: 2px solid  rgb(0, 85, 255);")
        self.CPU.setAlignment(QtCore.Qt.AlignCenter)
        self.CPU.setObjectName("CPU")


        self.Memory = QtWidgets.QLabel(self.centralwidget)
        self.Memory.setGeometry(QtCore.QRect(30, 110, 71, 41))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Memory.setFont(font)
        self.Memory.setStyleSheet("color: rgb(0, 85, 255);\n"
"border: 2px solid  rgb(0, 85, 255);")
        self.Memory.setAlignment(QtCore.Qt.AlignCenter)
        self.Memory.setObjectName("Memory")



        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 60, 211, 41))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 85, 255);\n"
"border: 2px solid  rgb(0, 85, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")




        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 110, 211, 41))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(0, 85, 255);\n"
"border: 2px solid  rgb(0, 85, 255);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")


        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(440, 500, 591, 111))
        self.textEdit.setStyleSheet("background-color: transparent;\n"
"color: rgb(0, 85, 255);\n"
"border:none;\n"
"padding: 2px 6px;")
        self.textEdit.setObjectName("textEdit")


        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(890, 160, 411, 151))
        font = QtGui.QFont()
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(1, 132, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")

        self.mainLabel.raise_()
        self.cammandArea.raise_()
        self.dateLabel.raise_()
        self.timeLabel.raise_()
        self.buttonsLabel.raise_()
        self.startButton.raise_()
        self.stopButton.raise_()
        self.centerJarvisLabel.raise_()
        self.featuresLabel.raise_()
        self.plainTextEdit.raise_()
        self.label.raise_()
        self.performanceLabel.raise_()
        self.label_2.raise_()
        self.CPU.raise_()
        self.Memory.raise_()

        self.label_3.raise_()
        self.label_5.raise_()
        self.textEdit.raise_()
        self.label_7.raise_()
        JarvisUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(JarvisUI)
        QtCore.QMetaObject.connectSlotsByName(JarvisUI)

    def retranslateUi(self, JarvisUI):
        _translate = QtCore.QCoreApplication.translate
        JarvisUI.setWindowTitle(_translate("JarvisUI", "MainWindow"))
        self.dateLabel.setText(_translate("JarvisUI", "DATE : "))
        self.timeLabel.setText(_translate("JarvisUI", "TIME : "))
        self.buttonsLabel.setText(_translate("JarvisUI", "TextLabel"))
        self.startButton.setText(_translate("JarvisUI", "START"))
        self.stopButton.setText(_translate("JarvisUI", "EXIT"))
        self.featuresLabel.setText(_translate("JarvisUI", "TextLabel"))
        self.label.setText(_translate("JarvisUI", "FEATURES"))
        self.performanceLabel.setText(_translate("JarvisUI", "TextLabel"))
        self.label_2.setText(_translate("JarvisUI", "PERFORMANCE"))
        self.CPU.setText(_translate("JarvisUI", "CPU"))
        self.Memory.setText(_translate("JarvisUI", "Memory"))
        
        self.textEdit.setText(_translate("JarvisUI", ""))
        self.label_7.setText(_translate("JarvisUI", "NOVA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisUI = QtWidgets.QMainWindow()
    ui = Ui_JarvisUI()
    ui.setupUi(JarvisUI)
    JarvisUI.show()
    sys.exit(app.exec_())
